name: ${artifactId}
version: ${version}
author: ${author}
description: ${description}
website: ${url}
main: ${mainClass}

commands:
  stationaryentity:
    aliases: [ste]
    description: "${description}"
    usage: |
      §6[StationaryEntity]§f Command list:
      §cUsage: §f/ste spawn <entity type> [NBT] §7- Spawn an entity which has the same position and rotation as you. The entity type is the same as in the vanilla summon command.
      §7You can also specify NBT tags: "/ste spawn villager Silent:1,Profession:2". The NoAI, Rotation and PersistenceRequired tags are always applied, but you override the Invulnerable and Silent tags by entering some yourself.
      §cUsage: §f/ste name <name> §7- Add an always visible name to the next right clicked entity.
      §cUsage: §f/ste delete §7- Delete the next right clicked entity safely.
      §cUsage: §f/ste clear [radius] §7- Clear the surroundings of floating, always visible names. The default radius is 1 block.
      §cUsage: §f/ste stop §7- Exit the selecting mode you joined to by entering the name/delete command.